server:
  port: 8080

grpc:
  server:
    port:
      9002

spring:
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://auth-service:4008
          predicates:
            - Path=/auth/**

        - id: user_service
          uri: http://localhost:4000
          predicates:
            - Path=/admin/**
          filters:
            - JwtValidation
logging:
  level:
    org.springframework.cloud.gateway: DEBUG