server:
  port: 8080

spring:
  cloud:
    gateway:
      globals:
        corsConfigurations:
          '[/**]':
            allowedHeaders:
              - "*"
            exposedHeaders:
              - X-User-Id
              - X-Roles
      routes:
        - id: auth_service
          uri: http://auth-service:4008
          predicates:
            - Path=/auth/**
          filters:

        - id: user_service
          uri: http://user-service:4000
          predicates:
            - Path=/admin/**
          filters:
            - JwtValidation

        - id: partners_service
          uri: http://partners-service:4006
          predicates:
              - Path=/partners/**
          filters:
            - JwtValidation
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.sp.gateway: DEBUG